### ISSUE TITLE
Uncaught NameError in __init__.py line 533

### ISSUE THREAD

**Issue by islamsaka** [Aider-AI/aider#2116] opened 2024-10-22 16:28 UTC
Aider version: 0.59.1
Python version: 3.12.7
Platform: macOS-15.0.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 757, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 233, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 967, in cmd_help
    res = install_help_extra(self.io)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "help.py", line 24, in install_help_extra
    res = utils.check_pip_install_extra(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 330, in check_pip_install_extra
    __import__(module)
  File "__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "base.py", line 28, in <module>
    from sentence_transformers import SentenceTransformer
  File "__init__.py", line 9, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "__init__.py", line 3, in <module>
    from .CrossEncoder import CrossEncoder
  File "CrossEncoder.py", line 9, in <module>
    import torch
  File "__init__.py", line 533, in <module>
    for name in dir(_C):
                    ^^
NameError: name '_C' is not defined

```

**Comment by paul-gauthier** [comment] 2024-10-22 20:34
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1904. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-22 20:34 UTC
