### ISSUE TITLE
Uncaught AttributeError in llm.py line 35

### ISSUE THREAD

**Issue by zanagraf** [Aider-AI/aider#2211] opened 2024-10-31 06:27 UTC
Aider version: 0.60.1
Python version: 3.12.7
Platform: Linux-6.6.58-1-lts-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.6.58-1-lts (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 585, in main
    main_model = models.Model(
                 ^^^^^^^^^^^^^
  File "models.py", line 737, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 937, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 35, in _load_litellm
    self._lazy_module._logging._disable_debugging()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm' has no attribute '_logging'

```

**Comment by paul-gauthier** [comment] 2024-10-31 20:42
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1401. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-31 20:42 UTC
