### ISSUE TITLE
Uncaught SwitchCoder in commands.py line 1044

### ISSUE THREAD

**Issue by fr34k8** [Aider-AI/aider#2297] opened 2024-11-08 00:42 UTC
Aider version: 0.62.1
Python version: 3.12.7
Platform: macOS-15.0.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 564, in main
    return main(argv, input, output, right_repo_root, return_coder=return_coder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 796, in main
    commands.cmd_load(args.load)
  File "commands.py", line 1287, in cmd_load
    self.run(cmd)
  File "commands.py", line 236, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 1017, in cmd_ask
    return self._generic_chat_command(args, "ask")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 1044, in _generic_chat_command
    raise SwitchCoder(
aider.commands.SwitchCoder

```

**Comment by paul-gauthier** [comment] 2024-11-08 16:37
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2232. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-08 16:37 UTC
