### ISSUE TITLE
Uncaught ValueError in base_coder.py line 159

### ISSUE THREAD

**Issue by germanilia** [Aider-AI/aider#2448] opened 2024-11-24 11:33 UTC
Aider version: 0.64.2.dev67+ge56651e5
Python version: 3.12.4
Platform: macOS-15.1.1-arm64-i386-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 861, in main
    coder.run()
  File "base_coder.py", line 741, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 784, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1258, in send_message
    self.reply_completed()
  File "architect_coder.py", line 36, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 159, in create
    raise ValueError(f"Unknown edit format {edit_format}")
ValueError: Unknown edit format json

```

**Comment by paul-gauthier** [comment] 2024-11-26 14:46
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2431. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.

**Closed by paul-gauthier** 2024-11-26 14:46 UTC
