### ISSUE TITLE
Uncaught ValueError in base_coder.py line 156

### ISSUE THREAD

**Issue by calmren** [Aider-AI/aider#2184] opened 2024-10-29 06:42 UTC
Aider version: 0.60.2.dev43+ged4ad45e
Python version: 3.11.9
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.47.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 710, in main
    coder.run(test_errors)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1197, in send_message
    self.reply_completed()
  File "architect_coder.py", line 33, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 156, in create
    raise ValueError(f"Unknown edit format {edit_format}")
ValueError: Unknown edit format json

```

**Comment by paul-gauthier** [comment] 2024-10-29 21:51
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1835. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-29 21:51 UTC
