### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by acacio** [Aider-AI/aider#2037] opened 2024-10-11 21:55 UTC
Aider version: 0.59.1
Python version: 3.9.6
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "openai.py", line 810, in completion
    raise e
  File "openai.py", line 705, in completion
    return self.streaming(
  File "openai.py", line 935, in streaming
    headers, response = self.make_sync_openai_chat_completion_request(
  File "openai.py", line 605, in make_sync_openai_chat_completion_request
    raise e
  File "openai.py", line 594, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
  File "_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
  File "_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "completions.py", line 742, in create
    return self._post(
  File "_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "_base_client.py", line 954, in request
    return self._request(
  File "_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01j9yrvsy6ftqbdbqk3v5zetmh` on tokens per minute (TPM): Limit 6000, Used 0, Requested 20736. Please try again in 2m27.36s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1407, in completion
    response = groq_chat_completions.completion(
  File "handler.py", line 41, in completion
    return super().completion(
  File "openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01j9yrvsy6ftqbdbqk3v5zetmh` on tokens per minute (TPM): Limit 6000, Used 0, Requested 20736. Please try again in 2m27.36s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "base_coder.py", line 1129, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1414, in send
    hash_object, completion = send_completion(
  File "sendchat.py", line 83, in send_completion
    res = litellm.completion(**kwargs)
  File "utils.py", line 1070, in wrapper
    raise e
  File "utils.py", line 958, in wrapper
    result = original_function(*args, **kwargs)
  File "main.py", line 2957, in completion
    raise exception_type(
  File "exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "exception_mapping_utils.py", line 393, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: GroqException - Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01j9yrvsy6ftqbdbqk3v5zetmh` on tokens per minute (TPM): Limit 6000, Used 0, Requested 20736. Please try again in 2m27.36s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 757, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1131, in send_message
    except retry_exceptions() as err:
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
AttributeError: module 'litellm.llms.anthropic.chat' has no attribute 'AnthropicError'

```

**Comment by paul-gauthier** [comment] 2024-10-15 13:54
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1414. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-15 13:54 UTC
