### ISSUE TITLE
Uncaught OSError in __init__.py line 379

### ISSUE THREAD

**Issue by ssh713** [Aider-AI/aider#2265] opened 2024-11-05 18:16 UTC
Aider version: 0.62.0
Python version: 3.12.7
Platform: macOS-13.4-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 22.5.0 (64bit)
Git version: git version 2.45.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 828, in main
    coder.run()
  File "base_coder.py", line 738, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 781, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1163, in send_message
    chunks = self.format_messages()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1097, in format_messages
    chunks = self.format_chat_chunks()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1047, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 635, in get_repo_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 607, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 128, in get_repo_map
    files_listing = self.get_ranked_tags_map(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 547, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 612, in get_ranked_tags_map_uncached
    tree = self.to_tree(ranked_tags[:middle], chat_rel_fnames)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 695, in to_tree
    output += self.render_tree(cur_abs_fname, cur_fname, lois)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 651, in render_tree
    context = TreeContext(
              ^^^^^^^^^^^^
  File "grep_ast.py", line 47, in __init__
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
  File "__init__.py", line 132, in __init__
    self.lib = cdll.LoadLibrary(fspath(path_or_ptr))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/shahzadsherazi/codes/myenv/lib/python3.12/site-packages/tree_sitter_languages/languages.so, 0x0006): tried: '/Users/shahzadsherazi/codes/myenv/lib/python3.12/site-packages/tree_sitter_languages/languages.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/shahzadsherazi/codes/myenv/lib/python3.12/site-packages/tree_sitter_languages/languages.so' (no such file), '/Users/shahzadsherazi/codes/myenv/lib/python3.12/site-packages/tree_sitter_languages/languages.so' (no such file)

```

**Comment by paul-gauthier** [comment] 2024-11-07 18:24
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1716. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-07 18:24 UTC
