### ISSUE TITLE
Uncaught AttributeError in downloader.py line 1068

### ISSUE THREAD

**Issue by HenryPrzygocki** [Aider-AI/aider#2063] opened 2024-10-15 23:14 UTC
Aider version: 0.59.1
Python version: 3.11.0
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.47.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 757, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 233, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 967, in cmd_help
    res = install_help_extra(self.io)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "help.py", line 24, in install_help_extra
    res = utils.check_pip_install_extra(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 330, in check_pip_install_extra
    __import__(module)
  File "__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "base.py", line 12, in <module>
    from llama_index.core.base.embeddings.base import (
  File "base.py", line 14, in <module>
    from llama_index.core.callbacks.base import CallbackManager
  File "__init__.py", line 10, in <module>
    from llama_index.core.base.response.schema import Response
  File "schema.py", line 9, in <module>
    from llama_index.core.schema import NodeWithScore
  File "schema.py", line 27, in <module>
    from llama_index.core.utils import SAMPLE_TEXT, truncate_text
  File "utils.py", line 89, in <module>
    globals_helper = GlobalsHelper()
                     ^^^^^^^^^^^^^^^
  File "utils.py", line 45, in __init__
    import nltk
  File "__init__.py", line 180, in <module>
    from nltk.downloader import download, download_shell
  File "downloader.py", line 2475, in <module>
    _downloader = Downloader()
                  ^^^^^^^^^^^^
  File "downloader.py", line 515, in __init__
    self._download_dir = self.default_download_dir()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "downloader.py", line 1068, in default_download_dir
    for nltkdir in nltk.data.path:
                   ^^^^^^^^^
AttributeError: partially initialized module 'nltk' has no attribute 'data' (most likely due to a circular import)

```

**Comment by paul-gauthier** [comment] 2024-10-23 21:07
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Closed by paul-gauthier** 2024-10-23 21:06 UTC

**Comment by ghbakir** [comment] 2024-11-19 17:45
For me this happened _after_ aider updated.

**Comment by ghbakir** [comment] 2024-11-19 17:50
Sorry pressed send too early.
Information from my system
aider 0.63.2

>aider
Aider v0.63.2
Model: gemini/gemini-1.5-flash-latest with whole edit format
Git repo: .git with 27 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
──────────────────────────────────────────────────────────────────────────────────────
> /help load

2024-11-19 18:48:37.413517: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(my note: Stats generating embeddings....)

(why it does some embedding computation on help  is odd)

i can not reproduce for now. 

i guess the fact that its happened on load is a red herring.

**Comment by paul-gauthier** [comment] 2024-11-19 17:56
How did you install aider?

**Comment by ghbakir** [comment] 2024-11-19 18:01
https://aider.chat/docs/install/install.html#maclinux-install

**Comment by paul-gauthier** [comment] 2024-11-19 19:54
You python environment looks like it has the wrong dependencies. See the troubleshooting docs:

https://aider.chat/docs/troubleshooting/imports.html
