### ISSUE TITLE
Bug Aider with VertexAI anthorophic last version

### ISSUE THREAD

**Issue by xavitg** [Aider-AI/aider#2439] opened 2024-11-23 13:32 UTC
### Issue

I am using vertexai anthophic last version and I get this error when trying to talk with claude 3.5 last version when I add an image to the chat (.png file).
litellm.InternalServerError: VertexAIException InternalServerError - b'{"type":"error","error":{"type":"invalid_request_error","message":"Unexpected value(s) `pdfs-2024-09-25` for 
the `anthropic-beta` header. Please consult our documentation at docs.anthropic.com or try again without the header."}}'
The API provider's servers are down or overloaded.
Retrying in 0.2 seconds...
litellm.InternalServerError: VertexAIException InternalServerError - b'{"type":"error","error":{"type":"invalid_request_error","message":"Unexpected value(s) `pdfs-2024-09-25` for 
the `anthropic-beta` header. Please consult our documentation at docs.anthropic.com or try again without the header."}}'
The API provider's servers are down or overloaded.
Retrying in 0.5 seconds...
litellm.InternalServerError: VertexAIException InternalServerError - b'{"type":"error","error":{"type":"invalid_request_error","message":"Unexpected value(s) `pdfs-2024-09-25` for 
the `anthropic-beta` header. Please consult our documentation at docs.anthropic.com or try again without the header."}}'
The API provider's servers are down or overloaded.
Retrying in 1.0 seconds...

I started having this problem since Aider 0.61.0

### Version and model info

Aider 0.64.0
Version: vertexai anthrophic claude3.5 last version.

**Comment by paul-gauthier** [comment] 2024-12-03 15:52
Thanks for trying aider and filing this issue.

Aider isn't configured to send the BETA headers to Vertex. How have you configured aider with vertex? Do you still see this with the latest v0.66 aider?

**Comment by wottpal** [comment] 2024-12-10 17:16
Did you manage to resolve this, @xavitg?

**Comment by paul-gauthier** [comment] 2024-12-10 17:19
This looks like a duplicate of #2447. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-12-10 17:19 UTC
Labels: question
