### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by Dammi0815** [Aider-AI/aider#2047] opened 2024-10-13 16:52 UTC
Aider version: 0.59.1
Python version: 3.12.6
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.47.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "utils.py", line 7654, in chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 7197, in handle_ollama_stream
    raise e
  File "utils.py", line 7172, in handle_ollama_stream
    raise Exception(f"Ollama Error - {json_chunk}")
Exception: Ollama Error - {'error': 'error reading llm response: read tcp 127.0.0.1:54430->127.0.0.1:52289: wsarecv: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "base_coder.py", line 1129, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1425, in send
    yield from self.show_send_output_stream(completion)
  File "base_coder.py", line 1492, in show_send_output_stream
    for chunk in completion:
                 ^^^^^^^^^^
  File "ollama.py", line 376, in ollama_completion_stream
    raise e
  File "ollama.py", line 373, in ollama_completion_stream
    for transformed_chunk in streamwrapper:
                             ^^^^^^^^^^^^^
  File "utils.py", line 8219, in __next__
    raise exception_type(
  File "utils.py", line 8131, in __next__
    response: Optional[ModelResponse] = self.chunk_creator(chunk=chunk)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 8043, in chunk_creator
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "exception_mapping_utils.py", line 2107, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: Ollama Error - {'error': 'error reading llm response: read tcp 127.0.0.1:54430->127.0.0.1:52289: wsarecv: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.'}
Traceback (most recent call last):
  File "utils.py", line 7654, in chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 7197, in handle_ollama_stream
    raise e
  File "utils.py", line 7172, in handle_ollama_stream
    raise Exception(f"Ollama Error - {json_chunk}")
Exception: Ollama Error - {'error': 'error reading llm response: read tcp 127.0.0.1:54430->127.0.0.1:52289: wsarecv: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.'}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 757, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1131, in send_message
    except retry_exceptions() as err:
           ^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm.llms.anthropic.chat' has no attribute 'AnthropicError'

```

**Comment by paul-gauthier** [comment] 2024-10-15 13:54
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1414. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-15 13:54 UTC
