### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by NakedGreeen** [Aider-AI/aider#2463] opened 2024-11-26 09:06 UTC
Aider version: 0.57.1
Python version: 3.12.7
Platform: macOS-14.5-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.5.0 (64bit)
Git version: git version 2.36.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    if not main_model.streaming:
            ^^^^^^^^^^^
  File "base_coder.py", line 723, in run
    self.num_reflections = 0
                ^^^^^^^^^^^^^
  File "base_coder.py", line 766, in run_one
    if self.commands.is_command(inp):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1193, in send_message
  File "base_coder.py", line 1874, in auto_commit
    res.append(edit)
      ^^^^^^^^^^^^^^^
  File "repo.py", line 102, in commit
  File "repo.py", line 187, in get_commit_message
    ]
      
  File "sendchat.py", line 38, in wrapper
    kwargs["tool_choice"] = {"type": "function", "function": {"name": function["name"]}}
        ~~^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    stream=stream,
AttributeError: module 'litellm.llms.anthropic.chat' has no attribute 'AnthropicError'

```

**Comment by paul-gauthier** [comment] 2024-11-26 14:45
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1414. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.

**Closed by paul-gauthier** 2024-11-26 14:45 UTC
