### ISSUE TITLE
Bug report: Commit messages includes the prompt response

### ISSUE THREAD

**Issue by dekubu** [Aider-AI/aider#2149] opened 2024-10-25 07:54 UTC
Aider version: 0.60.0
Python version: 3.12.7
Platform: macOS-15.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

Aider v0.60.0
Main model: anthropic/claude-3-5-sonnet-20241022 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 84 files
Repo-map: using 1024 tokens, auto refresh

The auto commit is adding partial prompt response in to the commit.
It is an intermittent problem, so very hard to understand why.

**Comment by 5ocworkshop** [comment] 2024-10-25 08:25
I've seen entire conversations that went on for more than a screen, back and forth between the user and agent, in my commits yesterday.  There was even this loop of have a nice day, good bye, see you soon, we'll be talking kind of thing.

**Comment by dekubu** [comment] 2024-10-25 12:01
Yes exactly that , Opps I just realised I have added this twice.

**Comment by dekubu** [comment] 2024-10-25 12:02
https://github.com/Aider-AI/aider/issues/2154  << Is a more detailed version.

**Comment by 999AICoder** [comment] 2024-10-26 13:36
A proposed fix (by aider itself)

aider/repo.py


 <<<<<<< SEARCH
         commit_message = commit_message.strip()
         if commit_message and commit_message[0] == '"' and commit_message[-1] == '"':
             commit_message = commit_message[1:-1].strip()

         return commit_message
 =======
         # Clean up the commit message - take only the first line that looks like a commit message
         lines = commit_message.strip().splitlines()
         for line in lines:
             line = line.strip()
             # Skip empty lines
             if not line:
                 continue
             # Skip markdown code blocks
             if line.startswith("```") or line.startswith("~~~"):
                 continue
             # Skip lines that are clearly part of explanations
             if line.startswith(("Here", "I ", "The ", "This ", "Now", "Let's", "We ")):
                 continue
             # If we find a line that looks like a commit message (has a type prefix)
             if any(line.startswith(f"{t}:") or line.startswith(f"{t}(") for t in [
                 "fix", "feat", "build", "chore", "ci", "docs", "style", "refactor", "perf", "test"
             ]):
                 # Remove quotes if present
                 if line[0] == '"' and line[-1] == '"':
                     line = line[1:-1].strip()
                 return line

         # If we didn't find a properly formatted message, take the first non-empty line
         for line in lines:
             line = line.strip()
             if line and not line.startswith(("```", "~~~")):
                 if line[0] == '"' and line[-1] == '"':
                     line = line[1:-1].strip()
                 return line

         return commit_message
 >>>>>>> REPLACE

**Comment by 999AICoder** [comment] 2024-10-26 13:37
aider/repo.py


```
 <<<<<<< SEARCH
         commit_message = commit_message.strip()
         if commit_message and commit_message[0] == '"' and commit_message[-1] == '"':
             commit_message = commit_message[1:-1].strip()

         return commit_message
 =======
         # Clean up the commit message - take only the first line that looks like a commit message
         lines = commit_message.strip().splitlines()
         for line in lines:
             line = line.strip()
             # Skip empty lines
             if not line:
                 continue
             # Skip markdown code blocks
             if line.startswith("```") or line.startswith("~~~"):
                 continue
             # Skip lines that are clearly part of explanations
             if line.startswith(("Here", "I ", "The ", "This ", "Now", "Let's", "We ")):
                 continue
             # If we find a line that looks like a commit message (has a type prefix)
             if any(line.startswith(f"{t}:") or line.startswith(f"{t}(") for t in [
                 "fix", "feat", "build", "chore", "ci", "docs", "style", "refactor", "perf", "test"
             ]):
                 # Remove quotes if present
                 if line[0] == '"' and line[-1] == '"':
                     line = line[1:-1].strip()
                 return line

         # If we didn't find a properly formatted message, take the first non-empty line
         for line in lines:
             line = line.strip()
             if line and not line.startswith(("```", "~~~")):
                 if line[0] == '"' and line[-1] == '"':
                     line = line[1:-1].strip()
                 return line

         return commit_message
 >>>>>>> REPLACE
```

**Comment by dekubu** [comment] 2024-10-27 02:19
@999AICoder  does this solve the problem? if so THANK YOU!

**Comment by 999AICoder** [comment] 2024-10-27 15:53
@dekubu that change has not been verified yet. will test next week to and propose a PR if appropriate. there is probably an upstream bug so this most likely does not address the root cause

**Comment by dekubu** [comment] 2024-10-27 18:40
Way Cool. I appreciate the efforts, thanks

**Comment by paul-gauthier** [comment] 2024-10-31 22:43
Thanks for trying aider and filing this issue.

You can use a more capable model for the weak model, which will make it less likely to generate weird commit messages.

Unfortunately, aider can't enforce "one line commit message" because some folks may use a commit prompt that allows multi-line commit messages.

**Comment by paul-gauthier** [comment] 2024-10-31 22:44
This looks like a duplicate of #2154. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-31 22:44 UTC
Labels: question
