### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by inivert** [Aider-AI/aider#2420] opened 2024-11-21 20:00 UTC
Aider version: 0.57.1
Python version: 3.12.6
Platform: macOS-15.2-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.2.0 (64bit)
Git version: git version 2.23.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "openai.py", line 854, in completion
    raise e
  File "openai.py", line 749, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "openai.py", line 959, in streaming
    openai_client: OpenAI = self._get_openai_client(  # type: ignore
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "openai.py", line 577, in _get_openai_client
    _new_client = OpenAI(
                  ^^^^^^^
  File "_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1602, in completion
    raise e
  File "main.py", line 1575, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "openai.py", line 864, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "base_coder.py", line 1115, in send_message
    try:
        ^
  File "base_coder.py", line 1392, in send
    ]
      
  File "sendchat.py", line 87, in send_completion
    if retry_delay > RETRY_TIMEOUT:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 960, in wrapper
    raise e
  File "utils.py", line 849, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 3034, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "exception_mapping_utils.py", line 2125, in exception_type
    raise e
  File "exception_mapping_utils.py", line 310, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    coder = Coder.create(
        ^^^^^^^^^^^
  File "base_coder.py", line 723, in run
    self.num_reflections = 0
                ^^^^^^^^^^^^^
  File "base_coder.py", line 766, in run_one
    if self.commands.is_command(inp):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1117, in send_message
    model=self.main_model.name,
    ^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    stream=stream,
AttributeError: module 'litellm.llms.anthropic.chat' has no attribute 'AnthropicError'

```

**Comment by paul-gauthier** [comment] 2024-11-21 20:45
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1414. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.

**Closed by paul-gauthier** 2024-11-21 20:45 UTC
