### ISSUE TITLE
Uncaught ModuleNotFoundError in pagerank_alg.py line 453

### ISSUE THREAD

**Issue by jaypeeZero** [Aider-AI/aider#2105] opened 2024-10-22 03:22 UTC
Aider version: 0.59.1
Python version: 3.10.14
Platform: macOS-15.0-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.44.0

I was in the middle of using Aider inside VSCode.  
I `/read` 2 files into the context, both are simple Markdown files of bullet lists.

I told Aider to follow the instructions in the 2 files, and this is what I got.

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
  File "main.py", line 757, in main
  File "base_coder.py", line 730, in run
  File "base_coder.py", line 773, in run_one
  File "base_coder.py", line 1108, in send_message
  File "base_coder.py", line 1044, in format_messages
  File "base_coder.py", line 994, in format_chat_chunks
  File "base_coder.py", line 627, in get_repo_messages
  File "base_coder.py", line 599, in get_repo_map
  File "repomap.py", line 127, in get_repo_map
  File "repomap.py", line 491, in get_ranked_tags_map
  File "repomap.py", line 522, in get_ranked_tags_map_uncached
  File "repomap.py", line 399, in get_ranked_tags
  File "backends.py", line 412, in __call__
  File "pagerank_alg.py", line 110, in pagerank
  File "pagerank_alg.py", line 453, in _pagerank_scipy
ModuleNotFoundError: No module named 'scipy'

```

**Comment by paul-gauthier** [comment] 2024-10-22 20:40
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1673. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-22 20:40 UTC
