### ISSUE TITLE
Can't install with pip on python 3.13

### ISSUE THREAD

**Issue by boosh** [Aider-AI/aider#2513] opened 2024-12-02 10:48 UTC
### Issue

Trying to `pip install aider-chat` in a new venv with python 3.13.0 (mac) fails twice (at least):

1. setuptools is not in requirements.txt so needs manually installing to install distutils
2. The pinned version of numpy isn't compatible with python 3.13. A compatible version (1.26.4) can be installed manually, but aider pins specifically to 1.24.3 which can't be installed.

Aider should probably pin to `numpy~=1.24.3`, for >= that version, or just upgrade. There may be other errors but I can't get past that one.

The numpy error is:

    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### Version and model info

Aider 0.66.0, Python 3.13.0, pip=24.3.1, Mac.

**Comment by paul-gauthier** [comment] 2024-12-02 14:50
This looks like a duplicate of #1984. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-12-02 14:50 UTC
