### ISSUE TITLE
In architect mode, Aider appends to added file instead of creating new file

### ISSUE THREAD

**Issue by larryhudson** [Aider-AI/aider#2258] opened 2024-11-05 07:40 UTC
Hey there! First of all, thanks so much for all your work on Aider, it's an incredible tool.

I've been playing around with architect mode using Claude 3.5 Sonnet v2 as the architect model and Claude 3.5 Haiku as the editor model.

I've found a bug where the editor model should create a new file, but instead it appends the file contents to an 'added' file instead of creating a new file.

To reproduce this issue:
- Clone this small demo repository: https://github.com/larryhudson/demo-fastapi-sqlalchemy-pytest
- Run command to start Aider: `aider --sonnet --weak-model claude-3-5-haiku-20241022 --editor-model claude-3-5-haiku-20241022 --architect`
- Run inside Aider: `/add app/main.py`
- Send prompt: `I want to move the routes into a separate routes file and then import that as a 'router' in the main file.`
- The architect will describe the changes correctly, and the editor will send the changes to the new file path, which should trigger Aider to ask the user if a new file can be created. But instead, it appends the change to the end of the `app/main.py` file.

You can [see the full Aider chat history in this GitHub gist](https://gist.github.com/larryhudson/0dc8d4f4c1fe4629b23276e684537fee). And [the file contents of app/main.py after the change here](https://gist.github.com/larryhudson/7c7988c4f7715529093088a4d3a97524).

Let me know if you need any more details. Thanks again!

Aider version: 0.62.0
Python version: 3.12.4
Platform: macOS-14.3.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.3.0 (64bit)
Git version: git version 2.39.3 (Apple Git-145)

Aider v0.62.0
Main model: claude-3-5-sonnet-20241022 with architect edit format, infinite output
Editor model: claude-3-5-haiku-20241022 with editor-diff edit format
Weak model: claude-3-5-haiku-20241022
Git repo: .git with 9 files
Repo-map: using 1024 tokens, auto refresh
Added app/main.py to the chat.
Restored previous conversation history.

**Comment by 5ocworkshop** [comment] 2024-11-05 09:39
Not sure if this is the exact same issue or not, but I was am testing out Haiku (although I see with this Sonnet as well) and I created a new script.  I have been testing and refining it and I was getting strange results so I started scrolling through the code.  There were three different versions of the full code in the file.  There is definitely something going on with the search/replace not working as expected in the latest release.  I'm on:

Aider v0.62.0
Model: claude-3-5-haiku-20241022 with diff edit format, infinite output
Git repo: .git with 356 files

**Comment by mzehrer** [comment] 2024-11-05 10:37
I was also able to reproduce the described behavior in /code mode, regardless of whether I used sonnet or haiku. In the past,aider asked whether to create a new file before starting; now the content of the new file is simply appended to the existing file without any questions.

**Comment by 5ocworkshop** [comment] 2024-11-05 10:44
I use git to checkout 0.60.1 and so far I am not having any issue.

**Comment by bastiion** [comment] 2024-11-05 11:16
I am also affected by this bug using the following configuration:

```
Aider v0.62.0
Main model: claude-3-5-sonnet-20241022 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
```

downgrading to 0.59  for now

Thank you for all your work!

**Comment by nickredmark** [comment] 2024-11-05 15:30
same here

**Comment by paul-gauthier** [comment] 2024-11-05 15:33
Can you share some specific file names and output from aider where this happened?

**Comment by mzehrer** [comment] 2024-11-05 16:12
Here is output while editing a Svelte component. I removed the code parts. Besides not creating the new file, everything else was OK.

#### Refactor the Modal into a new component in the file EditAsset.svelte  

I'll help refactor the Modal component into a new EditAsset.svelte file. Here are the changes:

1. First, create the new EditAsset.svelte file:

src/frontend/src/components/EditAsset.svelte
```svelte
<<<<<<< SEARCH
=======

.... a lot of code

>>>>>>> REPLACE
```

2. Now update AssetDetails.svelte to use the new component:

src/frontend/src/components/AssetDetails.svelte
```svelte
<<<<<<< SEARCH

... even more code

=======

... again some code

>>>>>>> REPLACE
```

3. Update the imports in AssetDetails.svelte:

src/frontend/src/components/AssetDetails.svelte
```svelte
<<<<<<< SEARCH

... code

=======
    
... code    
    
>>>>>>> REPLACE
```

4. Remove the errors state from AssetDetails.svelte since it's now handled in EditAsset:

src/frontend/src/components/AssetDetails.svelte
```svelte
<<<<<<< SEARCH
    
... code     
    
=======

... code 

>>>>>>> REPLACE
```

These changes:
1. Extract all modal-related code into a new EditAsset component
2. Simplify AssetDetails by removing the modal code and using the new component
3. Move form validation and error handling to EditAsset
4. Use proper event dispatching between components

The EditAsset component is now a self-contained, reusable component that handles all the form logic and validation, while AssetDetails focuses on displaying asset information and managing the overall state.

> Tokens: 7.7k sent, 2.7k received.
Cost: $0.06 message, $0.19 session. Use --no-stream for accurate caching costs.  
> Applied edit to src/frontend/src/components/AssetDetails.svelte  
> Commit 31fc268 refactor: Extract Modal component into EditAsset.svelte  
> You can use /undo to undo and discard each aider commit.

**Comment by FelixLisczyk** [comment] 2024-11-05 16:25
> Can you share some specific file names and output from aider where this happened?

```
Aider v0.62.0
Main model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 2 files
Repo-map: using 1024 tokens, files refresh
Use /help <question> for help, run "aider --help" to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Read only files:
../../.aider.conventions.md
> /add "My File.txt"

Added /Users/felix/Downloads/aider-test/My File.txt to the chat
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Read only files:
../../.aider.conventions.md

Editable files:
My File.txt
> Create a new file 'text.txt' with contents 'Hello World'

I'll create a new text.txt file with the contents "Hello World":

text.txt


 <<<<<<< SEARCH
 =======
 Hello World
 >>>>>>> REPLACE


Tokens: 4.6k sent, 1.9k cache write, 50 received. Cost: $0.02 message, $0.02 session.
Applied edit to My File.txt
Commit b2b389d feat: add text.txt file with "Hello World" contents
You can use /undo to undo and discard each aider commit.
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Read only files:
../../.aider.conventions.md

Editable files:
My File.txt
```

**Comment by transcendr** [comment] 2024-11-05 16:43
I've also noticed some weirdness around creating new files the last couple versions. I always use architect mode so I don't know if it's the case for reg mode, however what happens is I'll get an error that the file doesn't exist in red text in the UI now, whereas before it would simply offer to create the new file. I'll then have to go and manually create, add the file to chat and run the prompt again. It doesn't seem to happen consistently though.

**Comment by paul-gauthier** [comment] 2024-11-05 17:15
Ok, this should be fixed.  Thanks for the helpful bug reports and detailed debugging info.

The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by 999AICoder** [comment] 2024-11-05 17:50
That appears to have resolved the issue for me @paul-gauthier

**Comment by FelixLisczyk** [comment] 2024-11-05 18:10
It's working in my sample project. Thank you for the quick fix! 😊

```
Aider v0.62.1.dev18+gc71a92ac
Main model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite output
Weak model: claude-3-5-haiku-20241022
Git repo: .git with 2 files
Repo-map: using 1024 tokens, files refresh
Use /help <question> for help, run "aider --help" to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Read only files:
../../.aider.conventions.md
> /add "My File.txt"

Added /Users/felix/Downloads/aider-test/My File.txt to the chat
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Read only files:
../../.aider.conventions.md

Editable files:
My File.txt
> Create a new file 'text.txt' with contents 'Hello World'

I'll create a new text.txt file with the contents "Hello World":

text.txt


 <<<<<<< SEARCH
 =======
 Hello World
 >>>>>>> REPLACE


Tokens: 4.6k sent, 1.9k cache hit, 45 received. Cost: $0.0092 message, $0.0092 session.

text.txt
Create new file? (Y)es/(N)o [Yes]: Y
Applied edit to text.txt
Commit d77f7ea feat: Add text.txt with initial content
You can use /undo to undo and discard each aider commit.
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Read only files:
../../.aider.conventions.md

Editable files:
My File.txt text.txt
```

**Comment by 5ocworkshop** [comment] 2024-11-05 18:16
While it is likely a different issue, I am still getting duplicate functions in my files after editing, even with the latest update.  If I roll back to .59.1 this stops.

**Comment by kennyfrc** [comment] 2024-11-06 02:01
I just tried the latest main branch on my side (ie. asked haiku to create 2 files, then asked it again to move it to another repo), and it worked without a hitch.

**Comment by paul-gauthier** [comment] 2024-11-06 02:41
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Closed** 2024-11-06 02:41 UTC
Labels: bug, fixed
