### ISSUE TITLE
Python 3.1.3 no module named Distutils 

### ISSUE THREAD

**Issue by thesolomon-tech** [Aider-AI/aider#2206] opened 2024-10-30 22:36 UTC
### Issue

Hello,

I have found when attempting to install on a Windows machine with Python 3.13 that an error would occur:
"import distutils.core ModuleNotFoundError: No module named 'distutils'"

Thanks

**Comment by paul-gauthier** [comment] 2024-10-31 23:56
This looks like a duplicate of #1984. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-31 23:56 UTC
