### ISSUE TITLE
Uncaught TypeError in repomap.py line 200

### ISSUE THREAD

**Issue by akrajan** [Aider-AI/aider#2291] opened 2024-11-07 18:51 UTC
Aider version: 0.62.1
Python version: 3.10.15
Platform: FreeBSD-14.1-RELEASE-p5-amd64-64bit-ELF
Python implementation: CPython
Virtual environment: No
OS: FreeBSD 14.1-RELEASE-p5 (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "repomap.py", line 251, in get_tags
    self.TAGS_CACHE[cache_key] = {"mtime": file_mtime, "data": data}
  File "core.py", line 823, in __setitem__
    self.set(key, value, retry=True)
  File "core.py", line 808, in set
    self._row_insert(db_key, raw, now, columns)
  File "core.py", line 857, in _row_insert
    sql(
sqlite3.OperationalError: no such column: "size" - should this be a string literal in single-quotes?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repomap.py", line 192, in tags_cache_error
    new_cache[test_key] = "test"
  File "core.py", line 823, in __setitem__
    self.set(key, value, retry=True)
  File "core.py", line 808, in set
    self._row_insert(db_key, raw, now, columns)
  File "core.py", line 857, in _row_insert
    sql(
sqlite3.OperationalError: no such column: "size" - should this be a string literal in single-quotes?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 827, in main
    coder.run()
  File "base_coder.py", line 738, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 781, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1163, in send_message
    chunks = self.format_messages()
  File "base_coder.py", line 1097, in format_messages
    chunks = self.format_chat_chunks()
  File "base_coder.py", line 1047, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
  File "base_coder.py", line 635, in get_repo_messages
    repo_content = self.get_repo_map()
  File "base_coder.py", line 607, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
  File "repomap.py", line 128, in get_repo_map
    files_listing = self.get_ranked_tags_map(
  File "repomap.py", line 549, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
  File "repomap.py", line 580, in get_ranked_tags_map_uncached
    ranked_tags = self.get_ranked_tags(
  File "repomap.py", line 400, in get_ranked_tags
    tags = list(self.get_tags(fname, rel_fname))
  File "repomap.py", line 254, in get_tags
    self.tags_cache_error(e)
  File "repomap.py", line 200, in tags_cache_error
    except (SQLITE_ERRORS, OSError) as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

```

**Comment by paul-gauthier** [comment] 2024-11-07 19:31
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2279. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-07 19:31 UTC
