### ISSUE TITLE
Disable code formatting

### ISSUE THREAD

**Issue by efunneko** [Aider-AI/aider#2138] opened 2024-10-24 14:17 UTC
### Issue

In my environment:

 * Windows, WSL2, terminal inside VSCode
 
When I am getting responses back from the model with code changes, my laptop seems to grind to a halt when it is displaying the code. My guess is that this is due to code formatting for the terminal, since it seems very fast to display all the text outside of the code. I would like to simply disable the code formatting/highlighting that is going on.

Note that this gets progressively slower the longer the code block is to the point where I am getting one line every few seconds.

### Version and model info

Aider 0.60.0
Model: Sonnet

**Comment by paul-gauthier** [comment] 2024-10-24 14:57
This looks like a duplicate of #930. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-24 14:57 UTC
