### ISSUE TITLE
Uncaught APIConnectionError in utils.py line 8159

### ISSUE THREAD

**Issue by Kokoabassplayer** [Aider-AI/aider#2175] opened 2024-10-28 13:54 UTC
Aider version: 0.60.0
Python version: 3.12.7
Platform: macOS-15.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "default.py", line 72, in map_httpcore_exceptions
  File "default.py", line 236, in handle_request
  File "connection_pool.py", line 216, in handle_request
  File "connection_pool.py", line 196, in handle_request
  File "connection.py", line 99, in handle_request
  File "connection.py", line 76, in handle_request
  File "connection.py", line 154, in _connect
  File "sync.py", line 152, in start_tls
  File "contextlib.py", line 158, in __exit__
  File "_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 1586, in completion
  File "chat.py", line 1139, in completion
  File "http_handler.py", line 373, in post
  File "http_handler.py", line 356, in post
  File "_client.py", line 926, in send
  File "_client.py", line 954, in _send_handling_auth
  File "_client.py", line 991, in _send_handling_redirects
  File "_client.py", line 1027, in _send_single_request
  File "default.py", line 235, in handle_request
  File "contextlib.py", line 158, in __exit__
  File "default.py", line 89, in map_httpcore_exceptions
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
  File "main.py", line 776, in main
  File "base_coder.py", line 730, in run
  File "base_coder.py", line 773, in run_one
  File "base_coder.py", line 1212, in send_message
  File "base_coder.py", line 1895, in auto_commit
  File "repo.py", line 110, in commit
  File "repo.py", line 195, in get_commit_message
  File "sendchat.py", line 46, in wrapper
  File "_sync.py", line 105, in retry
  File "sendchat.py", line 104, in simple_send_with_retries
  File "sendchat.py", line 85, in send_completion
  File "utils.py", line 1086, in wrapper
  File "utils.py", line 974, in wrapper
  File "main.py", line 2847, in completion
  File "utils.py", line 8194, in exception_type
  File "utils.py", line 8159, in exception_type
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: AnthropicException - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

```

**Comment by paul-gauthier** [comment] 2024-10-28 22:01
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1756. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-28 22:01 UTC
