### ISSUE TITLE
Uncaught ValueError in <frozen ntpath> line 791

### ISSUE THREAD

**Issue by RussellOKS** [Aider-AI/aider#2125] opened 2024-10-23 07:14 UTC
Aider version: 0.60.0
Python version: 3.12.0
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 11 (64bit)
Git version: git version 2.45.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 776, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
                   ^^^^^^^^^^^^^^^^
  File "base_coder.py", line 742, in get_input
    return self.io.get_input(
           ^^^^^^^^^^^^^^^^^^
  File "io.py", line 362, in get_input
    os.path.relpath(fname, root) for fname in (abs_read_only_fnames or [])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 791, in relpath
ValueError: path is on mount 'C:', start on mount 'W:'

```

**Comment by paul-gauthier** [comment] 2024-10-23 21:06
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1433. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Comment by RussellOKS** [comment] 2024-10-25 04:03
Thanks Paul for an incredibly useful tool - I absolutely love it and use it every day.

This issue has not been resolved as of v0.60.1 and it is easy to repeat with following steps. I am doing this on Windows 11 and all that detail was sent before.

Activate the venv which is on the C drive and run Aider and it works fine.
Activate the venv which is on the C drive and then change to drive W: and run Aider and it produces the error if version is above v.59

**Comment by paul-gauthier** [comment] 2024-10-25 14:37
I just pushed a fix for this. The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment] 2024-10-29 21:21
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Closed by paul-gauthier** 2024-10-29 21:21 UTC
Labels: bug, fixed

**Comment by RussellOKS** [comment] 2024-10-30 08:56
Hi Paul

Apologies for not getting back to you. I was really caught up in work and
found no problem if I moved my work to a directory on the C drive so moved
there and carried on working just fine.

However the issue is not yet resolved as I cannot run aider on a directory
on either D: or W: drives and assume it is probably about not being C.

I tried creating a venv on W drive and the same error was produced. The
drives I am referring to are fixed NVME drives.

I also tried mapping a drive to a share and that produced a different error
(pasted below) and Aider cannot start.

regards,
Russell

  File "io.py", line 693, in append_chat_history
    self.tool_error(
  File "io.py", line 629, in tool_error
    self._tool_message(message, strip, self.tool_error_color)
  File "io.py", line 621, in _tool_message
    self.append_chat_history(hist, linebreak=True, blockquote=True)
  File "io.py", line 693, in append_chat_history
    self.tool_error(
  File "io.py", line 629, in tool_error
    self._tool_message(message, strip, self.tool_error_color)
  File "io.py", line 621, in _tool_message
    self.append_chat_history(hist, linebreak=True, blockquote=True)
  File "io.py", line 693, in append_chat_history
    self.tool_error(
  File "io.py", line 629, in tool_error
    self._tool_message(message, strip, self.tool_error_color)
  File "io.py", line 621, in _tool_message
    self.append_chat_history(hist, linebreak=True, blockquote=True)
  File "io.py", line 690, in append_chat_history
    with self.chat_history_file.open("a", encoding=self.encoding,
errors="ignore") as f:

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
