### ISSUE TITLE
Uncaught TypeError in repomap.py line 200

### ISSUE THREAD

**Issue by lubok-dot** [Aider-AI/aider#2301] opened 2024-11-08 09:35 UTC
Aider version: 0.62.1
Python version: 3.12.4
Platform: Linux-5.15.0-1064-azure-x86_64-with-glibc2.31
Python implementation: CPython
Virtual environment: No
OS: Linux 5.15.0-1064-azure (64bit)
Git version: git version 2.45.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "repomap.py", line 213, in load_tags_cache
    self.TAGS_CACHE = Cache(path)
                      ^^^^^^^^^^^
  File "core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "core.py", line 2438, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repomap.py", line 185, in tags_cache_error
    shutil.rmtree(path)
  File "shutil.py", line 759, in rmtree
    _rmtree_safe_fd(stack, onexc)
  File "shutil.py", line 703, in _rmtree_safe_fd
    onexc(func, path, err)
  File "shutil.py", line 662, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=dirfd)
OSError: [Errno 39] Directory not empty: PosixPath('/mnt/batch/tasks/shared/LS_root/mounts/clusters/oliver-test/code/Users/oliver.pfante/rg-epd-advanced-analytics-v2-01/.aider.tags.cache.v3')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 695, in main
    coder = Coder.create(
            ^^^^^^^^^^^^^
  File "base_coder.py", line 155, in create
    res = coder(main_model, io, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 401, in __init__
    self.repo_map = RepoMap(
                    ^^^^^^^^
  File "repomap.py", line 60, in __init__
    self.load_tags_cache()
  File "repomap.py", line 215, in load_tags_cache
    self.tags_cache_error(e)
  File "repomap.py", line 200, in tags_cache_error
    except (SQLITE_ERRORS, OSError) as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

```

**Comment by paul-gauthier** [comment] 2024-11-08 13:18
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by paul-gauthier** [comment] 2024-11-08 16:37
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2279. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-08 16:37 UTC
Labels: question
