### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by wordpad25** [Aider-AI/aider#2170] opened 2024-10-27 22:13 UTC
Aider version: 0.54.12
Python version: 3.10.4
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.44.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 682, in main
    )
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1183, in send_message
    return
  File "base_coder.py", line 1862, in auto_commit
    try:
  File "repo.py", line 106, in commit
  File "repo.py", line 186, in get_commit_message
    dict(role="user", content=content),
  File "sendchat.py", line 38, in wrapper
    decorated_func = backoff.on_exception(
  File "sendchat.py", line 30, in retry_exceptions
    litellm.exceptions.Timeout,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by wordpad25** [comment] 2024-10-27 22:14
> create a new component called chat

Certainly! I'll create a new component called "chat" for you. Since you haven't shared any existing files or specified a particular framework, I'll assume   
we're creating a basic React component. I'll create a new file for this component.

Here's the SEARCH/REPLACE block to create the new component:

src/components/Chat.js


 <<<<<<< SEARCH
 =======
 import React from 'react';

 const Chat = () => {
   return (
     <div className="chat-container">
       <h2>Chat Component</h2>
       <div className="chat-messages">
         {/* Chat messages will be displayed here */}
       </div>
       <div className="chat-input">
         <input type="text" placeholder="Type your message..." />
         <button>Send</button>
       </div>
     </div>
   );
 };

 export default Chat;
 >>>>>>> REPLACE


This creates a new file Chat.js in the src/components directory. The component includes a basic structure for a chat interface with a messages area and an   
input field with a send button.

To use this component, you'll need to import it in your main App component or wherever you want to use it.

Since you're using Windows, here's a command to create the necessary directory structure (if it doesn't exist already) and the file:


 mkdir src\components & echo. > src\components\Chat.js


This command creates the src\components directory (if it doesn't exist) and creates an empty Chat.js file. After running this command, you can copy the      
contents of the SEARCH/REPLACE block into the Chat.js file.

Remember to integrate this component into your existing React application by importing and using it where needed. If you need any further assistance or      
modifications to this component, please let me know!


Tokens: 2.3k sent, 386 received. Cost: $0.01 message, $0.02 session.

src/components/Chat.js
Create new file? (Y)es/(N)o [Yes]: y
Applied edit to src/components/Chat.js

# Uncaught AttributeError in sendchat.py line 30

Aider version: 0.54.12
Python version: 3.10.4
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.44.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 682, in main
    )
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1183, in send_message
    return
  File "base_coder.py", line 1862, in auto_commit
    try:
  File "repo.py", line 106, in commit
  File "repo.py", line 186, in get_commit_message
    dict(role="user", content=content),
  File "sendchat.py", line 38, in wrapper
    decorated_func = backoff.on_exception(
  File "sendchat.py", line 30, in retry_exceptions
    litellm.exceptions.Timeout,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

Please consider reporting this bug to help improve aider!
Open a GitHub Issue pre-filled with the above error in your browser? (Y/n) y
Attempting to open the issue URL in your default web browser...
Browser window should be opened.


You can also use this URL to file the GitHub Issue:

https://github.com/paul-gauthier/aider/issues/new?body=Aider+version%3A+0.54.12%0APython+version%3A+3.10.4%0APlatform%3A+Windows-10-10.0.22631-SP0%0APython+implementation%3A+CPython%0AVirtual+environment%3A+No%0AOS%3A+Windows+10+%2864bit%29%0AGit+version%3A+git+version+2.44.0.windows.1%0A%0AAn+uncaught+exception+occurred%3A%0A%0A%60%60%60%0ATraceback+%28most+recent+call+last%29%3A%0A++File+%22runpy.py%22%2C+line+196%2C+in+_run_module_as_main%0A++++return+_run_code%28code%2C+main_globals%2C+None%2C%0A++File+%22runpy.py%22%2C+line+86%2C+in+_run_code%0A++++exec%28code%2C+run_globals%29%0A++File+%22__main__.py%22%2C+line+7%2C+in+%3Cmodule%3E%0A++++sys.exit%28main%28%29%29%0A++File+%22main.py%22%2C+line+682%2C+in+main%0A++++%29%0A++File+%22base_coder.py%22%2C+line+730%2C+in+run%0A++++self.run_one%28user_message%2C+preproc%29%0A++File+%22base_coder.py%22%2C+line+773%2C+in+run_one%0A++++list%28self.send_message%28message%29%29%0A++File+%22base_coder.py%22%2C+line+1183%2C+in+send_message%0A++++return%0A++File+%22base_coder.py%22%2C+line+1862%2C+in+auto_commit%0A++++try%3A%0A++File+%22repo.py%22%2C+line+106%2C+in+commit%0A++File+%22repo.py%22%2C+line+186%2C+in+get_commit_message%0A++++dict%28role%3D%22user%22%2C+content%3Dcontent%29%2C%0A++File+%22sendchat.py%22%2C+line+38%2C+in+wrapper%0A++++decorated_func+%3D+backoff.on_exception%28%0A++File+%22sendchat.py%22%2C+line+30%2C+in+retry_exceptions%0A++++litellm.exceptions.Timeout%2C%0AAttributeError%3A+module+%27litellm.llms.anthropic%27+has+no+attribute+%27AnthropicError%27%0A%0A%60%60%60&title=Uncaught+AttributeError+in+sendchat.py+line+30


Traceback (most recent call last):
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\main.py", line 682, in main
    )
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 1183, in send_message
    return
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 1862, in auto_commit
    try:
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\repo.py", line 106, in commit

  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\repo.py", line 186, in get_commit_message
    dict(role="user", content=content),
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\sendchat.py", line 38, in wrapper
    decorated_func = backoff.on_exception(
  File "C:\Users\wordp\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\sendchat.py", line 30, in retry_exceptions
    litellm.exceptions.Timeout,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

**Comment by paul-gauthier** [comment] 2024-10-28 22:02
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1414. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-28 22:02 UTC

**Comment by wordpad25** [comment] 2024-10-28 22:26
I did see issue #1414 and tried the suggested solution - uninstalling
LiteLLM and installing version 1.44.7 - the pasted log is when using this
version.

PS:
By the way, I was wondering why we don't have specific versions for
libraries specified in the requirements? Is that intentional so people do
upgrade dependencies and report issues?
