### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by kiwangho-apds** [Aider-AI/aider#2294] opened 2024-11-07 23:33 UTC
Aider version: 0.56.0
Python version: 3.10.8
Platform: macOS-13.7-arm64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 22.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-145)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1124, in send_message
    continue
  File "base_coder.py", line 1413, in send
    # drop sentence punctuation from the end
  File "base_coder.py", line 1396, in send
    return res
  File "sendchat.py", line 86, in send_completion
  File "utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
  File "main.py", line 1755, in completion
    response = anthropic_chat_completions.completion(
  File "handler.py", line 540, in completion
    completion_stream, headers = make_sync_call(
  File "handler.py", line 149, in make_sync_call
    response = client.post(
  File "http_handler.py", line 371, in post
    response = self.client.send(req, stream=stream)
  File "_client.py", line 926, in send
    response = self._send_handling_auth(
  File "_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "connection_pool.py", line 216, in handle_request
    raise exc from None
  File "connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "http11.py", line 143, in handle_request
    raise exc
  File "http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "ssl.py", line 1259, in recv
    return self.read(buflen)
  File "ssl.py", line 1132, in read
    return self._sslobj.read(len)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    io=io,
  File "base_coder.py", line 735, in run
    while True:
  File "base_coder.py", line 778, in run_one
  File "base_coder.py", line 1126, in send_message
    self.warming_pings_left -= 1
  File "sendchat.py", line 30, in retry_exceptions
    # litellm exceptions inherit from openai exceptions
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by paul-gauthier** [comment] 2024-11-08 16:38
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1414. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-08 16:38 UTC
