### ISSUE TITLE
Please make a vs code extension

### ISSUE THREAD

**Issue by kneelesh48** [Aider-AI/aider#2377] opened 2024-11-15 06:07 UTC
### Issue

aider has great reviews and I'd like to use it but I hate typing in the terminal (no mouse support).

I discovered you have a web gui but it's made in streamlit. Streamlit screams PROTOTYPE. At least put a bit more effort and make a react app.

I think you might be python developers and JS is unknown territory. Maybe you can ask some JS contributors for help and have the python aider as backend.

Please consider making a VS code extension.
Having a proper gui would dramatically increase the number of users of aider.

**Comment by paul-gauthier** [comment] 2024-11-20 18:40
This looks like a duplicate of #68. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-20 18:40 UTC
