### ISSUE TITLE
Uncaught TypeError in repomap.py line 200

### ISSUE THREAD

**Issue by joslopgar** [Aider-AI/aider#2356] opened 2024-11-13 07:34 UTC
Aider version: 0.62.1
Python version: 3.11.10
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "repomap.py", line 213, in load_tags_cache
    self.TAGS_CACHE = Cache(path)
                      ^^^^^^^^^^^
  File "core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "core.py", line 2431, in reset
    ((old_value,),) = sql(
                      ^^^^
sqlite3.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repomap.py", line 185, in tags_cache_error
    shutil.rmtree(path)
  File "shutil.py", line 752, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "shutil.py", line 703, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "shutil.py", line 701, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'cache.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 695, in main
    coder = Coder.create(
            ^^^^^^^^^^^^^
  File "base_coder.py", line 155, in create
    res = coder(main_model, io, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 401, in __init__
    self.repo_map = RepoMap(
                    ^^^^^^^^
  File "repomap.py", line 60, in __init__
    self.load_tags_cache()
  File "repomap.py", line 215, in load_tags_cache
    self.tags_cache_error(e)
  File "repomap.py", line 200, in tags_cache_error
    except (SQLITE_ERRORS, OSError) as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

```

**Comment by paul-gauthier** [comment] 2024-11-13 20:52
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2279. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-13 20:52 UTC
