### ISSUE TITLE
Uncaught ValueError in base_coder.py line 159

### ISSUE THREAD

**Issue by Reza300p** [Aider-AI/aider#2441] opened 2024-11-23 17:16 UTC
Aider version: 0.64.1
Python version: 3.10.11
Platform: Windows-10-10.0.22000-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 861, in main
    coder.run()
  File "base_coder.py", line 741, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 784, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1258, in send_message
    self.reply_completed()
  File "architect_coder.py", line 36, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
  File "base_coder.py", line 159, in create
    raise ValueError(f"Unknown edit format {edit_format}")
ValueError: Unknown edit format editor-diff-fenced

```

**Comment by paul-gauthier** [comment] 2024-11-24 03:24
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2431. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.

**Closed by paul-gauthier** 2024-11-24 03:24 UTC
