### ISSUE TITLE
Uncaught AttributeError in downloader.py line 1068

### ISSUE THREAD

**Issue by ghbakir** [Aider-AI/aider#2396] opened 2024-11-19 13:05 UTC
Aider version: 0.63.2
Python version: 3.11.7
Platform: macOS-10.16-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.4.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 841, in main
    coder.run()
  File "base_coder.py", line 741, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 767, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 241, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 213, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 984, in cmd_help
    res = install_help_extra(self.io)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "help.py", line 24, in install_help_extra
    res = utils.check_pip_install_extra(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 334, in check_pip_install_extra
    __import__(module)
  File "__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "base.py", line 12, in <module>
    from llama_index.core.base.embeddings.base import (
  File "base.py", line 14, in <module>
    from llama_index.core.callbacks.base import CallbackManager
  File "__init__.py", line 10, in <module>
    from llama_index.core.base.response.schema import Response
  File "schema.py", line 9, in <module>
    from llama_index.core.schema import NodeWithScore
  File "schema.py", line 27, in <module>
    from llama_index.core.utils import SAMPLE_TEXT, truncate_text
  File "utils.py", line 89, in <module>
    globals_helper = GlobalsHelper()
                     ^^^^^^^^^^^^^^^
  File "utils.py", line 45, in __init__
    import nltk
  File "__init__.py", line 180, in <module>
    from nltk.downloader import download, download_shell
  File "downloader.py", line 2475, in <module>
    _downloader = Downloader()
                  ^^^^^^^^^^^^
  File "downloader.py", line 515, in __init__
    self._download_dir = self.default_download_dir()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "downloader.py", line 1068, in default_download_dir
    for nltkdir in nltk.data.path:
                   ^^^^^^^^^
AttributeError: partially initialized module 'nltk' has no attribute 'data' (most likely due to a circular import)

```

**Comment by paul-gauthier** [comment] 2024-11-19 16:45
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2063. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.

**Closed by paul-gauthier** 2024-11-19 16:45 UTC
