### ISSUE TITLE
Uncaught AttributeError in configargparse.py line 1047

### ISSUE THREAD

**Issue by bitnom** [Aider-AI/aider#1931] opened 2024-10-05 11:34 UTC
Aider version: 0.59.0
Python version: 3.11.9
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.42.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 364, in main
    args, unknown = parser.parse_known_args(argv)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configargparse.py", line 938, in parse_known_args
    [self.get_command_line_key_for_unknown_config_file_setting(key)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configargparse.py", line 1047, in get_command_line_key_for_unknown_config_file_setting
    key_without_prefix_chars = key.strip(self.prefix_chars)
                               ^^^^^^^^^
AttributeError: 'bool' object has no attribute 'strip'

```

**Comment by lucacri** [comment] 2024-10-05 16:35
same error for me:

```
Aider version: 0.59.0
Python version: 3.12.6
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 364, in main
    args, unknown = parser.parse_known_args(argv)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configargparse.py", line 938, in parse_known_args
    [self.get_command_line_key_for_unknown_config_file_setting(key)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configargparse.py", line 1047, in get_command_line_key_for_unknown_config_file_setting
    key_without_prefix_chars = key.strip(self.prefix_chars)
                               ^^^^^^^^^
AttributeError: 'bool' object has no attribute 'strip'
```

I am going to check my config file to see if that's an issue

**Comment by fry69** [comment] 2024-10-05 16:40
Thank you for filing this issue. This might a regression due to this change -> https://aider.chat/HISTORY.html#v0590

```
Renamed --yes to --yes-always.

    - Now uses AIDER_YES_ALWAYS env var and yes-always: yaml key.
    - Existing YAML and .env files will need to be updated.
    - Can still abbreviate to --yes on the command line.
```

**Comment by lucacri** [comment] 2024-10-05 16:47
You are correct, @fry69! For anyone else: if you have multiple .aider.conf files, remember that they all extend the .aider.conf file. In my case, I had another .aider-paid.conf, and I removed the yes: true from the aider-paid.conf, but it was still setting the value in the .aider.conf.

**Comment by andyhennie** [comment] 2024-10-05 17:27
any workaround for this issue?

**Comment by fry69** [comment] 2024-10-05 18:13
> any workaround for this issue?

Change
```yaml
yes: true
```
to
```yaml
yes-always: true
```
in all `.aider.conf.yml` files

**Comment by fry69** [comment] 2024-10-05 19:40
A fix has been pushed and is available in version `0.59.1`

Please update with ->
```
aider --update
```
aider will not detect the new version for up to day by itself as it caches the version.

**Comment by fry69** [comment] 2024-10-09 15:45
Another breaking change concerning `aider.config.yml` files:

Previously this worked ->
```yaml
assistant-output-color: #66b8ff
```
Now (`0.59.0`+) with full YAML syntax this no longer works, `#` marks the hex color as a comment.
The `#` hex color needs to be encapsulated in quotes now ->
```yaml
assistant-output-color: "#66b8ff"
```

**Comment by paul-gauthier** [comment] 2024-10-21 17:34
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Closed by paul-gauthier** 2024-10-21 17:34 UTC
Labels: bug, fixed
