### ISSUE TITLE
Completion for chat text is causing significant pauses during typing

### ISSUE THREAD

**Issue by efunneko** [Aider-AI/aider#2139] opened 2024-10-24 14:20 UTC
### Issue

This issue seems to be new with 0.60.0 (perhaps because it offers so many more completion options). I find typing in the chat very painful because I will get ~ 1 second pauses as it tries to figure out the set of completions to present. 

I would be completely happy to just have an option to disable this, since I almost never select anything from the completion and even if there is no delay, the white box popping up constantly is somewhat distracting.

Sorry to be asking for some much. I really appreciate this tool.

### Version and model info

Aider 0.60.0
Model Sonnet

**Comment by paul-gauthier** [comment] 2024-10-24 14:57
This looks like a duplicate of #930. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-24 14:57 UTC
