### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by yeahboi233** [Aider-AI/aider#2477] opened 2024-11-27 18:59 UTC
Aider version: 0.65.1
Python version: 3.10.14
Platform: macOS-15.1.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.45.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 887, in main
    coder.run()
  File "base_coder.py", line 758, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 801, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1304, in send_message
    lint_errors = self.lint_edited(edited)
  File "base_coder.py", line 1392, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
  File "linter.py", line 116, in lint
    res += tree_context(rel_fname, code, lintres.lines)
  File "linter.py", line 237, in tree_context
    context = TreeContext(
  File "grep_ast.py", line 47, in __init__
    parser = get_parser(lang)
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by paul-gauthier** [comment] 2024-11-28 23:44
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1236. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.

**Closed by paul-gauthier** 2024-11-28 23:44 UTC
