### ISSUE TITLE
Uncaught TypeError in repomap.py line 200

### ISSUE THREAD

**Issue by Yona544** [Aider-AI/aider#2290] opened 2024-11-07 16:39 UTC
Aider version: 0.62.2.dev2+g49fc1b40
Python version: 3.11.4
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "main.py", line 827, in main
    coder.run()
  File "base_coder.py", line 738, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 775, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 764, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 236, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 123, in cmd_chat_mode
    raise SwitchCoder(
aider.commands.SwitchCoder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repomap.py", line 213, in load_tags_cache
    self.TAGS_CACHE = Cache(path)
                      ^^^^^^^^^^^
  File "core.py", line 499, in __init__
    sql(query, (key, value))
  File "core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: disk I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repomap.py", line 185, in tags_cache_error
    shutil.rmtree(path)
  File "shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\\\\192.168.0.35\\YonaVmDataShare\\Projects\\posexport\\.aider.tags.cache.v3\\cache.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 835, in main
    coder = Coder.create(**kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 155, in create
    res = coder(main_model, io, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 401, in __init__
    self.repo_map = RepoMap(
                    ^^^^^^^^
  File "repomap.py", line 60, in __init__
    self.load_tags_cache()
  File "repomap.py", line 215, in load_tags_cache
    self.tags_cache_error(e)
  File "repomap.py", line 200, in tags_cache_error
    except (SQLITE_ERRORS, OSError) as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

```

**Comment by paul-gauthier** [comment] 2024-11-07 18:24
Thanks for trying aider and filing this issue.

This looks like a duplicate of #2279. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-11-07 18:24 UTC
